defaults:
  - _self_
  - model: resnet

train:
  data_dir: "/mnt/disks/whole/init-train/"
  lr: 0.001
  batch_size: 32
  num_workers: 4
  val_split: 0.2
  class_weights: [1.0, 1.0]
  epochs: 10
  save_model: True
  out_dir: "out/" # ${now:%Y-%m-%d_%H-%M-%S}"

test:
  data_dir_pos: "/mnt/disks/whole/parasite-slides-cleaned/"
  data_dir_neg: "/mnt/disks/whole/whole-slides/"
  batch_size: 32
  num_workers: 4
  out_dir: "out/"

evaluate:
  model_dir: "out/resnet_baseline_2"
  csv_dir: ${evaluate.model_dir}/csv
  out_dir: ${evaluate.model_dir}/thresholds

wandb:
  enabled: True
  project: "octopi"
  job_type: "train_resnet"
  name: "resnet_baseline"

hydra:
  run:
    dir: "."