defaults:
  - _self_
  - model: resnet # this is for the model group
  - override hydra/launcher: joblib

model_name: "resnet18"

wandb:
  enabled: True
  project: "octopi"
  job_type: "train_${model_name}"
  name: "run0"

hydra:
  run:
    dir: "."


train:
  data_dir: "/home/heguanglin/data/061724/init-train/"
  lr: 0.001
  batch_size: 32
  num_workers: 1
  val_split: 0.2
  class_weights: [1.0, 1.0]
  epochs: 10
  save_model: True
  out_dir: "out/${model_name}/"

test:
  data_dir_pos: "/home/heguanglin/data/061724/parasite-slides-cleaned/"
  data_dir_whole: "/mnt/disks/whole/whole-slides/"
  data_txt_neg: "utils/neg.txt"
  batch_size: 4096
  num_workers: 4
  out_dir: "out/${model_name}/"

evaluate:
  model_dir: "out/${model_name}/${wandb.name}"
  csv_dir: ${evaluate.model_dir}/csv
  out_dir: ${evaluate.model_dir}/thresholds

